# samples names and graph (as GENOME-SVLABEL if files GENOME.fa and SVLABEL.vcf.gz exist)
samples: "ERR903030 NA19240"
graph: 'hg38-hgsvc'
## Chromosome name prefix (use "" if chr names are in the form 1, 2, ...)
chr_prefix: "chr"
chrs: '1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X Y'
# Should the data be saved on S3 and, if yes, where?
s3save: False
s3root: 's3://bucket/hg38-hgsvc'
# memory
mem_xg: 60000
mem_snarls: 120000
mem_gcsa: 80000
mem_gbwt: 200000
mem_minimizer_index: 200000
mem_dist_index: 200000
mem_map: 40000
mem_pack: 100000
mem_call: 40000
mem_pgconvert: 60000
mem_augment: 70000
# cores used in multi-threaded steps
cores_xg: 16
cores_snarls: 8
cores_gcsa: 32
cores_minimizer_index: 32
cores_dist_index: 32
cores_split_reads: 8
cores_map: 16
cores_pack: 10
cores_call: 16
cores_augment: 8
# mapper can be either 'map', 'mpmap', or 'gaffe'
mapper: 'map'
# for minimizer/gaffe mapper
mink: 39
minw: 15
covern: 16
# number of reads per chunk
nb_split_reads: 20000000
